/*
 * This file is automatically generated by version.pl. DO NOT EDIT!
 */

char	*_build_release =	"opennsa-6.5.17-EA12";
char	*_build_tree =		"/projects/ntsw_sw18_scratch/sdkrel/openbcm/sdk";
char	*_build_user =		"ku931718";
char	*_build_host =		"lvnvda3240";
char	*_build_date =		"Thu Mar 12 10:52:30 2020";
char	*_build_datestamp =	"20200312";
char	*_build_arch =		"x86_64";
char	*_build_os =		"linux";
