/*
 * This file is automatically generated by version.pl. DO NOT EDIT!
 */

char	*_build_release =	"opennsa-6.5.17-EA10";
char	*_build_tree =		"/projects/ntsw_sw18_scratch/sdkrel/openbcm/sdk";
char	*_build_user =		"sdkrel";
char	*_build_host =		"lc-sj1-4850";
char	*_build_date =		"Thu Feb 13 15:14:09 2020";
char	*_build_datestamp =	"20200213";
char	*_build_arch =		"x86_64";
char	*_build_os =		"linux";
